-- --------------------------------------------------------
-- Host:                         192.168.1.250
-- Versión del servidor:         5.5.44-MariaDB-log - MariaDB Server
-- SO del servidor:              Linux
-- HeidiSQL Versión:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando datos para la tabla country: 253 rows
DELETE FROM `country`;
/*!40000 ALTER TABLE `country` DISABLE KEYS */;
INSERT INTO `country` (`country_id`, `name`, `iso_code_2`, `iso_code_3`, `address_format`, `postcode_required`, `status`) VALUES
	(1, 'Afganistán', 'AF', 'AFG', '', 0, 1),
	(2, 'Albania', 'AL', 'ALB', '', 0, 1),
	(3, 'Argelia', 'DZ', 'DZA', '', 0, 1),
	(4, 'Samoa Americana', 'AS', 'ASM', '', 0, 1),
	(5, 'Andorra', 'AD', 'AND', '', 0, 1),
	(6, 'Angola', 'AO', 'AGO', '', 0, 1),
	(7, 'Anguila', 'AI', 'AIA', '', 0, 1),
	(8, 'Antártida', 'AQ', 'ATA', '', 0, 1),
	(9, 'Antigua y Barbuda', 'AG', 'ATG', '', 0, 1),
	(10, 'Argentina', 'AR', 'ARG', '', 0, 1),
	(11, 'Armenia', 'AM', 'ARM', '', 0, 1),
	(12, 'Aruba', 'AW', 'ABW', '', 0, 1),
	(13, 'Australia', 'AU', 'AUS', '', 0, 1),
	(14, 'Austria', 'AT', 'AUT', '', 0, 1),
	(15, 'Azerbaiyán', 'AZ', 'AZE', '', 0, 1),
	(16, 'Bahamas', 'BS', 'BHS', '', 0, 1),
	(17, 'Bahrein', 'BH', 'BHR', '', 0, 1),
	(18, 'Bangladesh', 'BD', 'BGD', '', 0, 1),
	(19, 'Barbados', 'BB', 'BRB', '', 0, 1),
	(20, 'Bielorrusia', 'BY', 'BLR', '', 0, 1),
	(21, 'Bélgica', 'BE', 'BEL', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 0, 1),
	(22, 'Belice', 'BZ', 'BLZ', '', 0, 1),
	(23, 'Benín', 'BJ', 'BEN', '', 0, 1),
	(24, 'Bermudas', 'BM', 'BMU', '', 0, 1),
	(25, 'Bután', 'BT', 'BTN', '', 0, 1),
	(26, 'Bolivia', 'BO', 'BOL', '', 0, 1),
	(27, 'Bosnia-Herzegovina', 'BA', 'BIH', '', 0, 1),
	(28, 'Botswana', 'BW', 'BWA', '', 0, 1),
	(29, 'Isla Bouvet', 'BV', 'BVT', '', 0, 1),
	(30, 'Brasil', 'BR', 'BRA', '', 0, 1),
	(31, 'Territorio Oceánico de las Indias Británicas', 'IO', 'IOT', '', 0, 1),
	(32, 'Brunei Darussalam', 'BN', 'BRN', '', 0, 1),
	(33, 'Bulgaria', 'BG', 'BGR', '', 0, 1),
	(34, 'Burkina Faso', 'BF', 'BFA', '', 0, 1),
	(35, 'Burundi', 'BI', 'BDI', '', 0, 1),
	(36, 'Camboya', 'KH', 'KHM', '', 0, 1),
	(37, 'Camerún', 'CM', 'CMR', '', 0, 1),
	(38, 'Canadá', 'CA', 'CAN', '', 0, 1),
	(39, 'Cabo Verde', 'CV', 'CPV', '', 0, 1),
	(40, 'Islas Caimán', 'KY', 'CYM', '', 0, 1),
	(41, 'República Centroafricana', 'CF', 'CAF', '', 0, 1),
	(42, 'Chad', 'TD', 'TCD', '', 0, 1),
	(43, 'Chile', 'CL', 'CHL', '', 0, 1),
	(44, 'China', 'CN', 'CHN', '', 0, 1),
	(45, 'Isla de Navidad', 'CX', 'CXR', '', 0, 1),
	(46, 'Islas Cocos', 'CC', 'CCK', '', 0, 1),
	(47, 'Colombia', 'CO', 'COL', '', 0, 1),
	(48, 'Comores', 'KM', 'COM', '', 0, 1),
	(49, 'República del Congo', 'CG', 'COG', '', 0, 1),
	(50, 'Islas Cook', 'CK', 'COK', '', 0, 1),
	(51, 'Costa Rica', 'CR', 'CRI', '', 0, 1),
	(52, 'Costa de Marfil', 'CI', 'CIV', '', 0, 1),
	(53, 'Croacia', 'HR', 'HRV', '', 0, 1),
	(54, 'Cuba', 'CU', 'CUB', '', 0, 1),
	(55, 'Chipre', 'CY', 'CYP', '', 0, 1),
	(56, 'República Checa', 'CZ', 'CZE', '', 0, 1),
	(57, 'Dinamarca', 'DK', 'DNK', '', 0, 1),
	(58, 'Yibuti', 'DJ', 'DJI', '', 0, 1),
	(59, 'Dominica', 'DM', 'DMA', '', 0, 1),
	(60, 'República Dominicana', 'DO', 'DOM', '', 0, 1),
	(61, 'Timor Oriental', 'TL', 'TLS', '', 0, 1),
	(62, 'Ecuador', 'EC', 'ECU', '', 0, 1),
	(63, 'Egipto', 'EG', 'EGY', '', 0, 1),
	(64, 'El Salvador', 'SV', 'SLV', '', 0, 1),
	(65, 'Guinea Ecuatorial', 'GQ', 'GNQ', '', 0, 1),
	(66, 'Eritrea', 'ER', 'ERI', '', 0, 1),
	(67, 'Estonia', 'EE', 'EST', '', 0, 1),
	(68, 'Etiopía', 'ET', 'ETH', '', 0, 1),
	(69, 'Islas Malvinas', 'FK', 'FLK', '', 0, 1),
	(70, 'Islas Feroe', 'FO', 'FRO', '', 0, 1),
	(71, 'Fyji', 'FJ', 'FJI', '', 0, 1),
	(72, 'Finlandia', 'FI', 'FIN', '', 0, 1),
	(74, 'Francia', 'FR', 'FRA', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 1, 1),
	(75, 'Guayana Francesa', 'GF', 'GUF', '', 0, 1),
	(76, 'Polinesia Francesa', 'PF', 'PYF', '', 0, 1),
	(77, 'Tierras Australes y Antárticas Francesas', 'TF', 'ATF', '', 0, 1),
	(78, 'Gabón', 'GA', 'GAB', '', 0, 1),
	(79, 'Gambia', 'GM', 'GMB', '', 0, 1),
	(80, 'Georgia', 'GE', 'GEO', '', 0, 1),
	(81, 'Alemania', 'DE', 'DEU', '{company}\r\n{firstname} {lastname}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 1, 1),
	(82, 'Ghana', 'GH', 'GHA', '', 0, 1),
	(83, 'Gibraltar', 'GI', 'GIB', '', 0, 1),
	(84, 'Grecia', 'GR', 'GRC', '', 0, 1),
	(85, 'Groenlandia', 'GL', 'GRL', '', 0, 1),
	(86, 'Granada', 'GD', 'GRD', '', 0, 1),
	(87, 'Guadalupe', 'GP', 'GLP', '', 0, 1),
	(88, 'Guam', 'GU', 'GUM', '', 0, 1),
	(89, 'Guatemala', 'GT', 'GTM', '', 0, 1),
	(90, 'República Guinea', 'GN', 'GIN', '', 0, 1),
	(91, 'Guinea Bissau', 'GW', 'GNB', '', 0, 1),
	(92, 'Guyana', 'GY', 'GUY', '', 0, 1),
	(93, 'Haití', 'HT', 'HTI', '', 0, 1),
	(94, 'Islas Heard y Mc Donald', 'HM', 'HMD', '', 0, 1),
	(95, 'Honduras', 'HN', 'HND', '', 0, 1),
	(96, 'Hong Kong', 'HK', 'HKG', '', 0, 1),
	(97, 'Hungría', 'HU', 'HUN', '', 0, 1),
	(98, 'Islandia', 'IS', 'ISL', '', 0, 1),
	(99, 'India', 'IN', 'IND', '', 0, 1),
	(100, 'Indonesia', 'ID', 'IDN', '', 0, 1),
	(101, 'Irán', 'IR', 'IRN', '', 0, 1),
	(102, 'Iraq', 'IQ', 'IRQ', '', 0, 1),
	(103, 'Irlanda', 'IE', 'IRL', '', 0, 1),
	(104, 'Israel', 'IL', 'ISR', '', 0, 1),
	(105, 'Italia', 'IT', 'ITA', '', 0, 1),
	(106, 'Jamaica', 'JM', 'JAM', '', 0, 1),
	(107, 'Japón', 'JP', 'JPN', '', 0, 1),
	(108, 'Jordania', 'JO', 'JOR', '', 0, 1),
	(109, 'Kazajstán', 'KZ', 'KAZ', '', 0, 1),
	(110, 'Kenia', 'KE', 'KEN', '', 0, 1),
	(111, 'Kiribati', 'KI', 'KIR', '', 0, 1),
	(112, 'Corea del Norte', 'KP', 'PRK', '', 0, 1),
	(113, 'Corea del Sur', 'KR', 'KOR', '', 0, 1),
	(114, 'Kuwait', 'KW', 'KWT', '', 0, 1),
	(115, 'Kirguistán', 'KG', 'KGZ', '', 0, 1),
	(116, 'Laos', 'LA', 'LAO', '', 0, 1),
	(117, 'Letonia', 'LV', 'LVA', '', 0, 1),
	(118, 'Líbano', 'LB', 'LBN', '', 0, 1),
	(119, 'Lesotho', 'LS', 'LSO', '', 0, 1),
	(120, 'Liberia', 'LR', 'LBR', '', 0, 1),
	(121, 'Libia', 'LY', 'LBY', '', 0, 1),
	(122, 'Liechtenstein', 'LI', 'LIE', '', 0, 1),
	(123, 'Lituania', 'LT', 'LTU', '', 0, 1),
	(124, 'Luxemburgo', 'LU', 'LUX', '', 0, 1),
	(125, 'Macao', 'MO', 'MAC', '', 0, 1),
	(126, 'Macedonia', 'MK', 'MKD', '', 0, 1),
	(127, 'Madagascar', 'MG', 'MDG', '', 0, 1),
	(128, 'Malawi', 'MW', 'MWI', '', 0, 1),
	(129, 'Malasia', 'MY', 'MYS', '', 0, 1),
	(130, 'Maldivas', 'MV', 'MDV', '', 0, 1),
	(131, 'Mali', 'ML', 'MLI', '', 0, 1),
	(132, 'Malta', 'MT', 'MLT', '', 0, 1),
	(133, 'Islas Marshall', 'MH', 'MHL', '', 0, 1),
	(134, 'Martinica', 'MQ', 'MTQ', '', 0, 1),
	(135, 'Mauritania', 'MR', 'MRT', '', 0, 1),
	(136, 'Mauricio', 'MU', 'MUS', '', 0, 1),
	(137, 'Mayotte', 'YT', 'MYT', '', 0, 1),
	(138, 'Mexico', 'MX', 'MEX', '', 0, 1),
	(139, 'Micronesia', 'FM', 'FSM', '', 0, 1),
	(140, 'Moldavia', 'MD', 'MDA', '', 0, 1),
	(141, 'Mónaco', 'MC', 'MCO', '', 0, 1),
	(142, 'Mongolia', 'MN', 'MNG', '', 0, 1),
	(143, 'Montserrat', 'MS', 'MSR', '', 0, 1),
	(144, 'Marruecos', 'MA', 'MAR', '', 0, 1),
	(145, 'Mozambique', 'MZ', 'MOZ', '', 0, 1),
	(146, 'Myanmar', 'MM', 'MMR', '', 0, 1),
	(147, 'Namibia', 'NA', 'NAM', '', 0, 1),
	(148, 'Nauru', 'NR', 'NRU', '', 0, 1),
	(149, 'Nepal', 'NP', 'NPL', '', 0, 1),
	(150, 'Paises Bajos', 'NL', 'NLD', '', 0, 1),
	(151, 'Antillas Holandesas', 'AN', 'ANT', '', 0, 1),
	(152, 'Nueva Caledonia', 'NC', 'NCL', '', 0, 1),
	(153, 'Nueva Zelanda', 'NZ', 'NZL', '', 0, 1),
	(154, 'Nicaragua', 'NI', 'NIC', '', 0, 1),
	(155, 'Niger', 'NE', 'NER', '', 0, 1),
	(156, 'Nigeria', 'NG', 'NGA', '', 0, 1),
	(157, 'Niue', 'NU', 'NIU', '', 0, 1),
	(158, 'Isla Norfolk', 'NF', 'NFK', '', 0, 1),
	(159, 'Marianas del Norte', 'MP', 'MNP', '', 0, 1),
	(160, 'Noruega', 'NO', 'NOR', '', 0, 1),
	(161, 'Omán', 'OM', 'OMN', '', 0, 1),
	(162, 'Pakistán', 'PK', 'PAK', '', 0, 1),
	(163, 'Palau', 'PW', 'PLW', '', 0, 1),
	(164, 'Panamá', 'PA', 'PAN', '', 0, 1),
	(165, 'Papúa-Nueva Guinea', 'PG', 'PNG', '', 0, 1),
	(166, 'Paraguay', 'PY', 'PRY', '', 0, 1),
	(167, 'Perú', 'PE', 'PER', '', 0, 1),
	(168, 'Filipinas', 'PH', 'PHL', '', 0, 1),
	(169, 'Isla Pitcairn', 'PN', 'PCN', '', 0, 1),
	(170, 'Polonia', 'PL', 'POL', '', 0, 1),
	(171, 'Portugal', 'PT', 'PRT', '', 0, 1),
	(172, 'Puerto Rico', 'PR', 'PRI', '', 0, 1),
	(173, 'Catar', 'QA', 'QAT', '', 0, 1),
	(174, 'Reunión', 'RE', 'REU', '', 0, 1),
	(175, 'Rumanía', 'RO', 'ROM', '', 0, 1),
	(176, 'Rusia', 'RU', 'RUS', '', 0, 1),
	(177, 'Ruanda', 'RW', 'RWA', '', 0, 1),
	(178, 'San Cristobal y Nevis', 'KN', 'KNA', '', 0, 1),
	(179, 'Sainta Lucía', 'LC', 'LCA', '', 0, 1),
	(180, 'San Vincente y Granadinas', 'VC', 'VCT', '', 0, 1),
	(181, 'Samoa', 'WS', 'WSM', '', 0, 1),
	(182, 'San Marino', 'SM', 'SMR', '', 0, 1),
	(183, 'Santo Tomé y Príncipe', 'ST', 'STP', '', 0, 1),
	(184, 'Arabia Saudita', 'SA', 'SAU', '', 0, 1),
	(185, 'Senegal', 'SN', 'SEN', '', 0, 1),
	(186, 'Seychelles', 'SC', 'SYC', '', 0, 1),
	(187, 'Sierra Leona', 'SL', 'SLE', '', 0, 1),
	(188, 'Singapur', 'SG', 'SGP', '', 0, 1),
	(189, 'Eslovaquia', 'SK', 'SVK', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city} {postcode}\r\n{zone}\r\n{country}', 0, 1),
	(190, 'Eslovenia', 'SI', 'SVN', '', 0, 1),
	(191, 'Islas Solomón', 'SB', 'SLB', '', 0, 1),
	(192, 'Somalia', 'SO', 'SOM', '', 0, 1),
	(193, 'Sudáfrica', 'ZA', 'ZAF', '', 0, 1),
	(194, 'Islas Sandwich del Sur', 'GS', 'SGS', '', 0, 1),
	(195, 'España', 'ES', 'ESP', '', 0, 1),
	(196, 'Sri Lanka', 'LK', 'LKA', '', 0, 1),
	(197, 'Santa Helena', 'SH', 'SHN', '', 0, 1),
	(198, 'St. Pierre and Miquelon', 'PM', 'SPM', '', 0, 1),
	(199, 'Sudán', 'SD', 'SDN', '', 0, 1),
	(200, 'Surinam', 'SR', 'SUR', '', 0, 1),
	(201, 'Islas Svalbard y Jan Mayen', 'SJ', 'SJM', '', 0, 1),
	(202, 'Swazilandia', 'SZ', 'SWZ', '', 0, 1),
	(203, 'Suecia', 'SE', 'SWE', '{company}\r\n{firstname} {lastname}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 1, 1),
	(204, 'Suiza', 'CH', 'CHE', '', 0, 1),
	(205, 'Siria', 'SY', 'SYR', '', 0, 1),
	(206, 'Taiwan', 'TW', 'TWN', '', 0, 1),
	(207, 'Tadjikistan', 'TJ', 'TJK', '', 0, 1),
	(208, 'Tanzania', 'TZ', 'TZA', '', 0, 1),
	(209, 'Tailandia', 'TH', 'THA', '', 0, 1),
	(210, 'Togo', 'TG', 'TGO', '', 0, 1),
	(211, 'Tokelau', 'TK', 'TKL', '', 0, 1),
	(212, 'Tonga', 'TO', 'TON', '', 0, 1),
	(213, 'Trinidad y Tobago', 'TT', 'TTO', '', 0, 1),
	(214, 'Túnez', 'TN', 'TUN', '', 0, 1),
	(215, 'Turquía', 'TR', 'TUR', '', 0, 1),
	(216, 'Turkmenistán', 'TM', 'TKM', '', 0, 1),
	(217, 'Islas Turcas y Caicos', 'TC', 'TCA', '', 0, 1),
	(218, 'Tuvalu', 'TV', 'TUV', '', 0, 1),
	(219, 'Uganda', 'UG', 'UGA', '', 0, 1),
	(220, 'Ucrania', 'UA', 'UKR', '', 0, 1),
	(221, 'Emiratos Árabes Unidos', 'AE', 'ARE', '', 0, 1),
	(222, 'Reino Unido', 'GB', 'GBR', '', 1, 1),
	(223, 'Estados Unidos', 'US', 'USA', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city}, {zone} {postcode}\r\n{country}', 0, 1),
	(224, 'Estados Unidos (Islas Menores)', 'UM', 'UMI', '', 0, 1),
	(225, 'Uruguay', 'UY', 'URY', '', 0, 1),
	(226, 'Uzbekistán', 'UZ', 'UZB', '', 0, 1),
	(227, 'Vanuatu', 'VU', 'VUT', '', 0, 1),
	(228, 'Ciudad del Vaticano', 'VA', 'VAT', '', 0, 1),
	(229, 'Venezuela', 'VE', 'VEN', '', 0, 1),
	(230, 'Vietnam', 'VN', 'VNM', '', 0, 1),
	(231, 'Islas Vírgenes Británicas', 'VG', 'VGB', '', 0, 1),
	(232, 'Islas Vírgenes Americanas', 'VI', 'VIR', '', 0, 1),
	(233, 'Islas Wallis y Futuna', 'WF', 'WLF', '', 0, 1),
	(234, 'Sáhara Occidental', 'EH', 'ESH', '', 0, 1),
	(235, 'Yemen', 'YE', 'YEM', '', 0, 1),
	(237, 'República Democrática del Congo', 'CD', 'COD', '', 0, 1),
	(238, 'Zambia', 'ZM', 'ZMB', '', 0, 1),
	(239, 'Zimbabwe', 'ZW', 'ZWE', '', 0, 1),
	(242, 'Montenegro', 'ME', 'MNE', '', 0, 1),
	(243, 'Serbia', 'RS', 'SRB', '', 0, 1),
	(244, 'Islas Aaland', 'AX', 'ALA', '', 0, 1),
	(245, 'Bonaire, Sint Eustatius y Saba', 'BQ', 'BES', '', 0, 1),
	(246, 'Curacao', 'CW', 'CUW', '', 0, 1),
	(247, 'Territorios Palestinos', 'PS', 'PSE', '', 0, 1),
	(248, 'Sudán del Sur', 'SS', 'SSD', '', 0, 1),
	(249, 'St. Barthelemy', 'BL', 'BLM', '', 0, 1),
	(250, 'St. Martin', 'MF', 'MAF', '', 0, 1),
	(251, 'Islas Canarias', 'IC', 'ICA', '', 0, 1),
	(252, 'Isla Ascensión', 'AC', 'ASC', '', 0, 1),
	(253, 'Kosovo', 'XK', 'UNK', '', 0, 1),
	(254, 'Isla de Man', 'IM', 'IMN', '', 0, 1),
	(255, 'Tristan da Cunha', 'TA', 'SHN', '', 0, 1),
	(256, 'Guernsey', 'GG', 'GGY', '', 0, 1),
	(257, 'Jersey', 'JE', 'JEY', '', 0, 1);
/*!40000 ALTER TABLE `country` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
